# Generated by Django 4.1 on 2022-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('run', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=21)),
                ('apellido_paterno', models.CharField(max_length=21)),
                ('apellido_materno', models.CharField(max_length=21)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
