# Generated by Django 4.1.1 on 2022-09-08 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_nacimiento',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='PreguntasCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('estado', models.IntegerField(default=0)),
                ('tipo_calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipocalidad')),
            ],
        ),
    ]
