# Generated by Django 4.1 on 2022-09-07 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_nacimiento',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=250)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.categoria')),
            ],
        ),
    ]
