# Generated by Django 4.1.1 on 2022-09-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_tipocalidad_alter_clientes_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntascalidad',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=8),
        ),
    ]
