# Generated by Django 4.1.1 on 2022-09-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_alter_preguntascalidad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntascalidad',
            name='ticket',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
