# Generated by Django 4.1.1 on 2022-09-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_categoria_alter_clientes_fecha_nacimiento_preguntas'),
        ('Clientes', '0005_alter_preguntascalidad_nombre_and_more'),
    ]

    operations = [
    ]
