# Generated by Django 4.1 on 2022-09-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_remove_preguntas_categoria_clientes_sexo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='sexo',
        ),
    ]
