# Generated by Django 4.1 on 2022-09-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_remove_clientes_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(default='Prefiere no decir', max_length=20),
        ),
    ]
